name: Send email after workflow

on:
  workflow_dispatch:

jobs:
  email-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: setup python environment
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install smtplib email
          
      - name: send email by executing python script
        run: python script.py
        env:
          WORKFLOW_NAME = ${{ github.workflow }}
          REPO_NAME = ${{ github.repository }}
          WORKFLOW_RUN_ID = ${{ github.run_id }}
          SENDER_EMAIL = ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD = ${{ secrets.SENDER_PASSWORD }}
          RECEIVER_EMAIL = ${{ secrets.RECEIVER_EMAIL }}